In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
'''
You're a data analyst and need to understand the age distribution of customers in your company's database. 
The customer ages are stored in a Pandas DataFrame named age_df. 
Your goal is to count the number of customers at each age to assist in demographic analysis for a targeted marketing campaign. 
Which command should you use?
Important: From the below options, copy paste the right selection to your answer section
age_df.groupby(Age").size()
age_df.groupby("Name", "Age").size()
age_df[age_df groupby("Name", "Age")] size()
age_dflage_df.groupby("Age")].size()strong text
'''

'\nYou\'re a data analyst and need to understand the age distribution of customers in your company\'s database. The customer ages are stored in a Pandas DataFrame named age_df. Your goal is to count the number of customers at each age to assist in demographic analysis for a targeted marketing campaign. Which command should you use?\nImportant: From the below options, copy paste the right selection to your answer section\nage_df.groupby(Age").size()\nage_df.groupby("Name", "Age").size()\nage_df[age_df groupby("Name", "Age")] size()\nage_dflage_df.groupby("Age")].size()strong text\n'

In [6]:
data = {'CustomerID': [1, 2, 3, 4, 5, 6],
        'Age': [25, 30, 25, 35, 30, 25]}
age_df = pd.DataFrame(data)

# Group by Age and count
age_distribution = age_df.groupby("Age")
age_distribution

In [7]:
age_distribution.size()

Age
25    3
30    2
35    1
dtype: int64

In [8]:
'''
You're a data analyst for a customer service-focused company. 
You need to analyze a DataFrame named feedback of that contains feedback id, category; sentiment_score, and response time. 
The goal is to compute the average sentiment score and average response time for each feedback category to identify areas for service improvement. 
What command should you execute to obtain these averages?
Important: From the below choices, copy paste the correct response into your answer
feedback df.groupby("category") ag g(("sentiment_score": "mean", "response_time": "mean"))
feedback_df.pivot_table(values= ['sentiment score", "response_time"], index="category", aggfunc="mean")
feedback df groupby("category") ['sentiment score", "response_time"] mean()
feedback df.groupby(["category']) apply(lambda x: x[["sentiment_score", "response time']].mean())

'''

'\nYou\'re a data analyst for a customer service-focused company. \nYou need to analyze a DataFrame named feedback of that contains feedback id, category; sentiment_score, and response time. \nThe goal is to compute the average sentiment score and average response time for each feedback category to identify areas for service improvement. \nWhat command should you execute to obtain these averages?\nImportant: From the below choices, copy paste the correct response into your answer\nfeedback df.groupby("category") ag g(("sentiment_score": "mean", "response_time": "mean"))\nfeedback_df.pivot_table(values= [\'sentiment score", "response_time"], index="category", aggfunc="mean")\nfeedback df groupby("category") [\'sentiment score", "response_time"] mean()\nfeedback df.groupby(["category\']) apply(lambda x: x[["sentiment_score", "response time\']].mean())\n\n'

In [9]:
data = {
    "feedback_id": [1, 2, 3, 4, 5, 6],
    "category": ["Delivery", "Product", "Delivery", "Customer Care", "Product", "Delivery"],
    "sentiment_score": [4.5, 3.8, 4.2, 3.5, 4.0, 4.8],
    "response_time": [30, 45, 25, 50, 40, 20],
}
feedback_df = pd.DataFrame(data)
feedback_df

feedback_id       category  sentiment_score  response_time
0            1       Delivery              4.5             30
1            2        Product              3.8             45
2            3       Delivery              4.2             25
3            4  Customer Care              3.5             50
4            5        Product              4.0             40
5            6       Delivery              4.8             20

In [11]:
feedback_df.groupby("category").agg({"sentiment_score": "mean", "response_time": "mean"})

sentiment_score  response_time
category                                     
Customer Care              3.5           50.0
Delivery                   4.5           25.0
Product                    3.9           42.5

In [12]:
feedback_df.pivot_table(values=["sentiment_score", "response_time"], index="category", aggfunc="mean")

response_time  sentiment_score
category                                     
Customer Care           50.0              3.5
Delivery                25.0              4.5
Product                 42.5              3.9

In [17]:
data = {
    "Product": ["A", "B", "A", "B", "C","A"],
    "Region": ["East", "West", "West", "East", "East","East"],
    "Sales": [200, 150, 300, 100, 250,100],
}
df = pd.DataFrame(data)
df

Product Region  Sales
0       A   East    200
1       B   West    150
2       A   West    300
3       B   East    100
4       C   East    250
5       A   East    100

In [18]:
result = df.pivot_table(values="Sales", index="Product", columns="Region", aggfunc="sum")
result

Region    East   West
Product              
A        300.0  300.0
B        100.0  150.0
C        250.0    NaN

In [26]:
a = np.array([1, 2])       # 1D array, shape: (2,)
a

array([1, 2])

In [27]:
a.size

2

In [28]:
a.shape

(2,)

In [30]:
b = np.array([[1, 2]])     # 2D array, shape: (1, 2)
b

array([[1, 2]])

In [31]:
b.shape

(1, 2)

In [37]:
df_a = pd.DataFrame(a)
df_a
# type(df_a)

0
0  1
1  2

In [39]:
df_a = pd.Series(a)
df_a
type(df_a)

pandas.core.series.Series

In [40]:
df_b = pd.DataFrame(b)
df_b

0  1
0  1  2

In [43]:
# df_b = pd.Series(b)   # ValueError: Data must be 1-dimensional

In [46]:
# explain with real time example, where to use  for 1d array and 2d array
"""Scenario:
You are working on a sales analysis project for a retail company. where number of store are 3

Example Data:
1D Array: Sales numbers for a single day.
1D arrays are suitable for data that does not have multiple attributes or dimensions.

2D Array: Sales numbers for multiple days, with each day represented as a row.
2D arrays are suitable for data with multiple dimensions (e.g., days vs. stores, products vs. categories, etc.).
You might use this to calculate store-wise totals or daily totals.
Use a 2D array when you have tabular data where each row corresponds to a day, and each column corresponds to a store's sales.
"""

# Sales numbers for 3 stores on a single day
sales_day1 = np.array([100, 150, 200])  # 1D array
sales_day1

array([100, 150, 200])

In [47]:
# Convert to a DataFrame
df_sales_day1 = pd.DataFrame(sales_day1)
df_sales_day1

0
0  100
1  150
2  200

In [54]:
# you might use this to calculate the total sales for the day
total_sales = np.sum(sales_day1)  # Output: 450
total_sales 

450

In [55]:
df_sales_day1 = pd.DataFrame(sales_day1, columns=['Sales'])
df_sales_day1

Sales
0    100
1    150
2    200

In [61]:
df_sales_day1.sum()

Sales    450
dtype: int64

In [56]:
# Sales numbers for 3 stores across 2 days
sales_multiple_days = np.array([[100, 150, 200], [120, 160, 210]])  # 2D array
sales_multiple_days

array([[100, 150, 200],
       [120, 160, 210]])

In [59]:
# Store-wise totals
store_totals = np.sum(sales_multiple_days, axis=0)  # Output: [220, 310, 410]
store_totals

array([220, 310, 410])

In [60]:
# Daily totals
daily_totals = np.sum(sales_multiple_days, axis=1)  # Output: [450, 490]
daily_totals

array([450, 490])

In [50]:
# Convert to a DataFrame
df_sales_multiple_days = pd.DataFrame(sales_multiple_days, columns=['Store1', 'Store2', 'Store3'])
df_sales_multiple_days

Store1  Store2  Store3
0     100     150     200
1     120     160     210

In [62]:
df_sales_multiple_days.sum()

Store1    220
Store2    310
Store3    410
dtype: int64

In [63]:
df_sales_multiple_days.sum(axis=1)

0    450
1    490
dtype: int64

### when to use pandas dataframe and when to use numpy array, explain with real time example

#### NumPy arrays are best suited for numerical data where you need to perform mathematical computations efficiently.

#### Suppose you're analyzing temperature data collected every hour for a week, and you want to calculate averages, variances, 
#### or perform matrix operations.

In [64]:
# Temperatures (7 days × 24 hours)
temperature_data = np.random.randint(15, 35, (7, 24))  # Random temperatures between 15-35°C
temperature_data

array([[18, 18, 16, 31, 30, 24, 28, 18, 22, 16, 22, 25, 34, 34, 29, 27,
        30, 33, 28, 23, 33, 25, 24, 20],
       [33, 33, 28, 19, 31, 29, 34, 32, 23, 22, 29, 26, 18, 31, 33, 31,
        25, 23, 28, 30, 31, 34, 25, 34],
       [26, 17, 22, 30, 23, 28, 31, 28, 22, 29, 32, 33, 19, 30, 15, 27,
        32, 17, 24, 18, 30, 30, 24, 16],
       [30, 33, 30, 27, 25, 27, 30, 32, 28, 21, 34, 24, 23, 30, 15, 31,
        16, 18, 17, 16, 23, 17, 34, 18],
       [26, 22, 24, 18, 31, 17, 16, 18, 18, 29, 30, 22, 33, 29, 29, 19,
        24, 32, 27, 15, 19, 15, 33, 17],
       [15, 22, 17, 25, 27, 21, 15, 23, 28, 27, 27, 19, 20, 25, 33, 21,
        21, 16, 15, 16, 15, 24, 30, 16],
       [16, 25, 25, 30, 23, 22, 22, 22, 15, 27, 21, 33, 15, 19, 23, 27,
        15, 17, 26, 31, 29, 18, 34, 34]])

In [67]:
hourly_avg = np.mean(temperature_data, axis=0)  # Average temp per hour
hourly_avg

array([23.42857143, 24.28571429, 23.14285714, 25.71428571, 27.14285714,
       24.        , 25.14285714, 24.71428571, 22.28571429, 24.42857143,
       27.85714286, 26.        , 23.14285714, 28.28571429, 25.28571429,
       26.14285714, 23.28571429, 22.28571429, 23.57142857, 21.28571429,
       25.71428571, 23.28571429, 29.14285714, 22.14285714])

In [68]:
daily_avg = np.mean(temperature_data, axis=1)  # Average temp per day
daily_avg 

array([25.33333333, 28.41666667, 25.125     , 24.95833333, 23.45833333,
       21.58333333, 23.70833333])

When to Use Pandas DataFrames
Pandas DataFrames are better for structured data where columns represent different features and rows represent records, especially when data includes labels, categories, or mixed data types.

Real-Time Example: Sales Analysis
Suppose you're analyzing a store's daily sales data that includes product names, categories, and prices.

In [69]:
sales_data = {
    'Product': ['A', 'B', 'C'],
    'Category': ['Electronics', 'Clothing', 'Grocery'],
    'Price': [100, 50, 20],
    'Quantity': [5, 10, 15]
}

# Create a DataFrame
df = pd.DataFrame(sales_data)
df

Product     Category  Price  Quantity
0       A  Electronics    100         5
1       B     Clothing     50        10
2       C      Grocery     20        15

In [70]:
total_revenue = (df['Price'] * df['Quantity']).sum()  # Calculate total revenue
total_revenue

1300

In [71]:
gr=df.groupby('Category')
gr

In [72]:
gr.agg({'Price':'sum'})

Price
Category          
Clothing        50
Electronics    100
Grocery         20

In [75]:
grouped_data = df.groupby('Category')['Price'].sum()
grouped_data

Category
Clothing        50
Electronics    100
Grocery         20
Name: Price, dtype: int64

In [95]:
'''Why Pandas?
    Designed for tabular data with labels.
    Provides powerful tools for grouping, filtering, and summarizing data.
    Handles mixed data types (e.g., strings, numbers) easily.
    Offers intuitive indexing and visualization options. '''
print()

In [94]:
''' Combine NumPy and Pandas  '''
print()

In [93]:
'''Real-Time Example: Marketing Campaign ROI
Data in Pandas: Store campaign data (cost, revenue, region).
NumPy Calculations: Calculate statistical metrics (e.g., ROI, variance).
python
Copy code
'''
print()

In [80]:
campaign_data = {
    'Campaign': ['A', 'B', 'C'],
    'Cost': [1000, 1500, 2000],
    'Revenue': [2000, 2500, 4000]
}
df = pd.DataFrame(campaign_data)
df

Campaign  Cost  Revenue
0        A  1000     2000
1        B  1500     2500
2        C  2000     4000

In [87]:
roi = np.array(df['Revenue']) / np.array(df['Cost'])-1
roi

array([1.        , 0.66666667, 1.        ])

In [88]:
df['ROI'] = roi

In [89]:
df

Campaign  Cost  Revenue       ROI
0        A  1000     2000  1.000000
1        B  1500     2500  0.666667
2        C  2000     4000  1.000000

In [96]:
'''
Summary: Which to Choose?

Use NumPy for:
Pure numerical computations (e.g., matrix operations, linear algebra).
Large numerical datasets with consistent data types.
Performance-critical operations.

Use Pandas for:
Structured, labeled data with mixed types.
Data wrangling, filtering, grouping, and summarization.
Handling missing values or performing operations on categorical data.
'''
print()

In [121]:
'''
In NumPy, the terms scalar, vector, and matrix refer to different types of arrays, each with distinct characteristics:

Scalar:

A scalar is a single numerical value.
In NumPy, it is represented as a 0-dimensional array.
Example: np.array(5) is a scalar.
Vector:

A vector is a 1-dimensional array (1D array), which can hold a sequence of numbers.
In NumPy, it can be created using np.array() with a list of values.
Example: np.array([1, 2, 3]) is a vector.
Matrix:

A matrix is a 2-dimensional array (2D array), which can represent a grid of numbers with rows and columns.
In NumPy, a matrix can be created by passing a list of lists or using a 2D array.
Example: np.array([[1, 2], [3, 4]]) is a matrix.
In summary:

Scalar: 0D array (single value).
Vector: 1D array (list of values). -- 2 types, Row Vector (1xN):  [6 7 8]  , shape=(2,)
                                             Column Vector (Nx1): [ [1] 
                                                                    [2] ]   shape=(2,1)
Matrix: 2D array (array of arrays). except shape(2,1) its always Column Vector (Nx1), 
matrix has more than one column
'''
a=''
column_vector = np.array([[1], [2]])
print(column_vector)

[[1]
 [2]]


scalars, vectors, and matrices can interact with each other

In [110]:
# 1. Scalar + Vector
scalar = 5
vector = np.array([1, 2, 3])
result = scalar + vector
print(result)

[6 7 8]


In [111]:
# 2. Scalar + Matrix
matrix = np.array([[1, 2], [3, 4]])
scalar = 3
result = scalar + matrix
print(result)

[[4 5]
 [6 7]]


In [112]:
# 3. Vector + Matrix

vector = np.array([1, 2])
matrix = np.array([[3, 4], [5, 6]])
result = vector + matrix
print(result)

[[4 6]
 [6 8]]


In [113]:
# 4. Matrix + Matrix
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = matrix1 + matrix2
print(result)

[[ 6  8]
 [10 12]]


In [114]:
# 5. Vector × Vector (Dot Product)

vector1 = np.array([1, 2])
vector2 = np.array([3, 4])
result = np.dot(vector1, vector2)
print(result)

11


In [115]:
# Matrix × Vector (Matrix-Vector Multiplication)
matrix = np.array([[1, 2], [3, 4]])
vector = np.array([5, 6])
result = np.dot(matrix, vector)
print(result)

[17 39]


In [118]:
# 7. Matrix × Matrix (Matrix Multiplication)
# Matrix multiplication (also known as the dot product of two matrices) 
# can be performed using np.dot() or the @ operator in Python
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2)
print(result)

[[19 22]
 [43 50]]


In [123]:
'''
vector has two types:
1. Row Vector (1xN): 
'''
row_vector = np.array([1, 2])
print(row_vector.shape)  # Output: (2,)

'''
2. Column Vector (Nx1):
'''
column_vector = np.array([[1], [2]])
print(column_vector.shape)  # Output: (2, 1)


(2,)
(2, 1)


In [ ]:
'''
Dot product of two vectors (1D arrays).
Dot product of two matrices (2D arrays) (same as matrix multiplication)
np.dot() or the @ operator to perform this operation in NumPy.
'''

In [124]:
# multiplying a matrix and a column vector in NumPy
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
print(A.shape)
v = np.array([[7], [8], [9]])
print(v)
print(v.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[7]
 [8]
 [9]]
(3, 1)


In [126]:
'''
For a 2D matrix, the shape is given by (rows, columns).
For a column vector, the shape is given by (rows, 1) where each element of the vector is placed in a separate row.
In a row vector, the shape is (1, columns) where all the elements are placed in a single row.

'''
print()

In [128]:
'''
the multiplication between a 2D matrix and a column vector always results in a column vector.
For matrix 𝐴  of shape ( 𝑚 , 𝑛 )  and a column vector v of shape ( 𝑛 , 1 ), 
the multiplication results in a column vector r of shape ( 𝑚 , 1 ).
'''
print()

In [130]:
'''
For example, 
if you set 𝐴0 = 0.3,
the resulting vector 𝐴 will be: 𝐴 = [ 0.3 , 0.7 ] 
if there is relationship 𝐴1 = 1 − 𝐴0   between two element of array.
1-0.3=0.7= A1
'''
print()

In [131]:
'''
Question: Solve Matrix Equations
Topics: Numpy


Write a Python Program using Numpy that solves the equation X = A*B*C and find the value of the vector A. In the equation, X is a scalar, A is the unknown 1x2 vector, B is a 2x2 matrix, and C is a 2x1 vector. Also, the two elements of A have the relationship A1=1-A0. Thus, given X, B, and C, as input, the program needs to print the value of the vector A using the equation X = A*B*C and the constraint A1=1-A0 

Note You need to print the value of vector A, rounded off to two decimal places. 
Important: Please write the proper code/answer in the answer section



solve the quetion and explain the answer with every step in simple way
'''
print()

In [133]:
X = 10  # Example scalar value
B = np.array([[2, 3], [1, 4]])  # 2x2 matrix
print(B)
C = np.array([[5], [7]])  # 2x1 vector
print(C)

[[2 3]
 [1 4]]
[[5]
 [7]]


In [135]:
BC = np.dot(B, C)  # Matrix multiplication of B and C
BC

array([[31],
       [33]])

In [136]:
# Simplify the equation X = A * BC
# Let BC be [p, q]. Then X = A0*p + A1*q
# Substituting A1 = 1 - A0, we get:
# X = A0*p + (1 - A0)*q
# X = A0*p + q - A0*q
# X = A0*(p - q) + q

p, q = BC.flatten()  # Extract elements of BC
p,q

(31, 33)

In [140]:
A0 = (X - q) / (p - q)  # Solve for A0
A1 = 1 - A0  # Solve for A1
A0,A1

(11.5, -10.5)

In [141]:
A = np.array([A0, A1])
print("Vector A:", A)

Vector A: [ 11.5 -10.5]


In [142]:
np.round(A, 2)

array([ 11.5, -10.5])

In [144]:
'''
Question: Manipulating Series
Topics: Pandas Series
 Sarah is given a series A containing N integers. She is also provided with X, ie, the integer that must be replaced with NaN. 
 She must perform the following operations on the array: 

Replace all occurrences of X with NaN. 
Calculate the mean of the remaining series. 
Count the number of occurrences of NaN in the series. 
Print the mean of the series and the count of occurrences of NaN on separate lines 

Note 1-based indexing is used. The mean is defined as the average of all the numbers in the data set. 
Important: Please write the proper code/answer in the answer section
'''
print()

In [145]:
import pandas as pd
import numpy as np

# Sample input
A = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9])  # Example series
X = 5  # The integer to replace with NaN

# Step 1: Replace all occurrences of X with NaN
A.replace(X, np.nan, inplace=True)

# Step 2: Calculate the mean of the remaining series (ignoring NaN)
mean_value = A.mean()

# Step 3: Count the number of NaN occurrences
nan_count = A.isna().sum()

# Print the results
print(f"Mean: {mean_value}")
print(f"Count of NaN: {nan_count}")


Mean: 5.0
Count of NaN: 1


In [146]:
Mean=np.round(mean_value,2)
Mean

5.0